# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Plan
    displayName: Init&Planning
    jobs:
      - job: 
        steps:
          - task: TerraformInstaller@1
            displayName: Installing terraform
            inputs:
              terraformVersion: '1.3.9'
          - task: TerraformTaskV4@4
            displayName: Terraform init command
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'azure_service'
              backendAzureRmResourceGroupName: 'rishabhpatel'
              backendAzureRmStorageAccountName: 'tfstorageaccount12'
              backendAzureRmContainerName: 'tf-container'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV4@4
            displayName: Terraform plan command
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-out="plan.out" -lock=false'
              environmentServiceNameAzureRM: 'azure_service'
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(system.defaultworkingdirectory)'
              Contents: '**'
              TargetFolder: '$(build.artifactstagingdirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  - stage: Deploying
    displayName: Applying
    dependsOn: Plan
    jobs:
      - deployment: Deploy
        environment: dev
        strategy:
            runOnce:
              deploy:
                steps:
                - task: TerraformInstaller@1
                  inputs:
                    terraformVersion: '1.3.9'
                - task: CopyFiles@2
                  inputs:
                    SourceFolder: '$(Pipeline.Workspace)/drop'
                    Contents: '**'
                    TargetFolder: '$(System.ArtifactsDirectory)'
                - task: TerraformTaskV4@4
                  displayName: Terraform init command
                  inputs:
                    provider: 'azurerm'
                    command: 'init'
                    workingDirectory: '$(System.ArtifactsDirectory)'
                    commandOptions: '-upgrade'
                    backendServiceArm: 'azure_service'
                    backendAzureRmResourceGroupName: 'rishabhpatel'
                    backendAzureRmStorageAccountName: 'tfstorageaccount12'
                    backendAzureRmContainerName: 'tf-container'
                    backendAzureRmKey: 'terraform.tfstate'
                - task: TerraformTaskV4@4
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    workingDirectory: '$(System.ArtifactsDirectory)'
                    commandOptions: '-lock=false "plan.out" '
                    environmentServiceNameAzureRM: 'azure_service'
                
                
                
                
          
          
   
