
trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Plan
    displayName: Init&Planning
    jobs:
      - job: 
        steps:
          - task: TerraformInstaller@1
            displayName: Installing terraform
            inputs:
              terraformVersion: '1.5.0'
          - task: TerraformTaskV4@4
            displayName: Terraform init command
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'azure_service'
              backendAzureRmResourceGroupName: 'rishabhpatel'
              backendAzureRmStorageAccountName: 'tfstorageaccount12'
              backendAzureRmContainerName: 'tf-container'
              backendAzureRmKey: 'pf/terraform.tfstate'
          - task: TerraformTaskV4@4
            displayName: Terraform plan command
            inputs:
              provider: 'azurerm'
              command: 'plan'
              commandOptions: '-out="plan.out"'
              environmentServiceNameAzureRM: 'azure_service'
          - script: ls -al $(system.defaultworkingdirectory)/.terraform/providers/registry.terraform.io/hashicorp/azuread/2.39.0/linux_amd64/terraform-provider-azuread_v2.39.0_x5
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(system.defaultworkingdirectory)'
              Contents: '**'
              TargetFolder: '$(build.artifactstagingdirectory)'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  - stage: Deploying
    displayName: Applying
    dependsOn: Plan
    jobs:
      - deployment: Deploy
        environment: dev
        strategy:
            runOnce:
              deploy:
                steps:
                - task: TerraformInstaller@1
                  inputs:
                    terraformVersion: '1.5.0'
            
                - script: chmod -R +x $(Pipeline.Workspace)/drop/.terraform/providers/registry.terraform.io
               


                - task: TerraformTaskV4@4
                  displayName: Terraform init command
                  inputs:
                    provider: 'azurerm'
                    command: 'init'
                    workingDirectory: '$(Pipeline.Workspace)/drop'
                    backendServiceArm: 'azure_service'
                    backendAzureRmResourceGroupName: 'rishabhpatel'
                    backendAzureRmStorageAccountName: 'tfstorageaccount12'
                    backendAzureRmContainerName: 'tf-container'
                    backendAzureRmKey: 'pf/terraform.tfstate'
                - task: TerraformTaskV4@4
                  inputs:
                    provider: 'azurerm'
                    command: 'apply'
                    workingDirectory: '$(Pipeline.Workspace)/drop'
                    commandOptions: '"plan.out" '
                    environmentServiceNameAzureRM: 'azure_service'
                
                
                
                
          
          
   
