trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
  - template: template.yml
    parameters:
      ProjectJson: project.json
      TerraformVars: terraform.tfvars
      backendServiceArm: azure_service
      backendAzureRmResourceGroupName: rishabhpatel
      backendAzureRmStorageAccountName: tfstorageaccount12
      backendAzureRmContainerName: tf-container
      backendAzureRmKey: azure/terraform.tfstate
      environmentServiceNameAzureRM: azure_service
      environment: dev
      
    
